---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

# Loading data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

# Plotly plots

## Scatterplot

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, 
    y = ~long, 
    type = "scatter", 
    mode = "markers",
    color = ~price, 
    text = ~text_label, 
    alpha = 0.5)
```

## Box plot

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, 
          color = ~neighbourhood, 
          type = "box", 
          colors = "viridis")
```

## Bar plot

Let's do a bar chart with number of rentals

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood,
    y = ~n,
    color = ~neighbourhood,
    type = "bar",
    colors = "viridis"
  )
```

## Other interesting things 

Check plotly cheat sheet!

```{r}
plot_ly(
  z = volcano,
  type = "heatmap"
)
```


Here's a choropleth.

```{r}
plot_ly(
  type = "choropleth",
  locations = c("AZ", "CA", "VT"),
  locationmode = "USA-states",
  colorscale = "Viridis",
  z = c(10, 20, 40)) %>% 
  layout(geo = list(scope = "usa"))
```


# ggplotly

Convert a ggplot object to an interactive graphic.

```{r}
ggp_scatter = 
nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatter)
```

